apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: cp-demo-k8s-workers
  labels:
    environment: "dev"
    role: "workers"
spec:
  forProvider:
    region: us-east-2
    clusterNameRef:
      name: cp-demo-k8s-cluster   
    instanceTypes:
      - t3.small
    nodeRoleRef:
      name: cp-demo-iam-k8s-worker-role
    subnetRefs:
      - name: cp-demo-k8s-private-1a
      - name: cp-demo-k8s-private-1b
    scalingConfig:
      desiredSize: 1
      maxSize: 3
      minSize: 1
  providerConfigRef:
    name: awsconfig