apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: cp-demo-k8s-private-rte-tbl
spec:
  forProvider:
    region: us-east-2
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: cp-demo-k8s-igw
    associations:
      - subnetIdRef:
          name: cp-demo-k8s-private-1a
      - subnetIdRef:
          name: cp-demo-k8s-private-1b
    tags:
    - key: Environment
      value: Demo
    - key: Owner
      value: crossplane
    - key: Name
      value: cp-demo-k8s-private-rte-tbl          
    vpcIdRef:
      name: cp-demo-k8s-vpc
  providerConfigRef:
    name: awsconfig
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: RouteTable
metadata:
  name: cp-demo-k8s-public-rte-tbl
spec:
  forProvider:
    region: us-east-2
    routes:
      - destinationCidrBlock: 0.0.0.0/0
        gatewayIdRef:
          name: cp-demo-k8s-igw
    associations:
      - subnetIdRef:
          name: cp-demo-k8s-public-1a
      - subnetIdRef:
          name: cp-demo-k8s-public-1b
    tags:
    - key: Environment
      value: Demo
    - key: Owner
      value: crossplane
    - key: Name
      value: cp-demo-k8s-public-rte-tbl          
    vpcIdRef:
      name: cp-demo-k8s-vpc
  providerConfigRef:
    name: awsconfig