apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: cp-demo-k8s-vpc
spec:
  forProvider:
    region: us-east-2
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
    - key: Environment
      value: Demo
    - key: Owner
      value: crossplane
    - key: Name
      value: cp-demo-k8s-vpc
  providerConfigRef:
    name: awsconfig